# Site settings
title: You might wanna know
email: marc[at]nospam.youmightwannaknow.org
description: > # this means to ignore newlines until "baseurl:"
  People make lots of claims about lots of things.
  You might wanna know how to find out whether those things are true or not for yourself.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.youmightwannaknow.org" # the base hostname & protocol for your site
github_username:  vegantriathlete

# Build settings
markdown: kramdown
